name: sub_project
description: "A new sub project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.6.6
  syncfusion_flutter_datepicker: ^28.1.35
  cached_network_image: ^3.4.1
  flutter_cache_manager: ^3.4.1
  shimmer: ^3.0.0
  smooth_page_indicator: ^1.2.0+3
  another_flushbar: ^1.12.30
  shared_preferences: ^2.3.4
  url_launcher: ^6.3.1
  webview_flutter: ^4.10.0
  either_dart: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  build_runner: ^2.4.12

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
  fonts:
    - family: poppins
      fonts:
        - asset: assets/fonts/SVN_Poppins_Regular.ttf
        - asset: assets/fonts/SVN_Poppins_Medium.ttf
          weight: 500
        - asset: assets/fonts/SVN_Poppins_SemiBold.ttf
          weight: 600
        - asset: assets/fonts/SVN_PoppinsBold.ttf
          weight: 700
